config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do      
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true, length: {minimum: 2}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  before_save :generate_slug!

  
  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.title)
    post = Post.find_by slug: the_slug            # 同じスラッグの投稿がすでにあるかどうかを確認
    count = 2
    while post && post != self                    # すでにある場合は
      the_slug = append_suffix(the_slug, count)   # 下記のappend_suffixメソッドを使用
      post = Post.find_by slug: the_slug          # 変更されたスラッグと同じものがあるか確認
      count += 1
    end
    self.slug = the_slug.downcase
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0              # タイトルの最後の要素が数字の場合
      return str.split('-').slice(0...-1).join('-') + "-" + count.to_s
    else                                          # タイトルの最後の要素が数字以外の場合
      return str + "-" + count                    #　カウンターの数字を追加
    end
  end

  def to_slug(name)
    str = name.strip                              # スペースを削除
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'           # アルファベット以外をダッシュに変換
    str.gsub! /-+/, "-"                           # 重複するダッシュを1つにまとめる
    self.slug = str.downcase                      # これがないと上のgsub!がnilを返してしまう
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "A new bookmark has been created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "The changes have been saved."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if vote.valid?
          flash[:notice] = "Thank you for voting!"
        else
          flash[:notice] = "You can only vote once for each bookmark."
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='well'>
  <%= form_for @post do |f| %>
    <div class='form-group'>
      <%= f.label :Title, class: "col-sm-2 control-label" %>
      <%= f.text_field :title, class: "form-control",autofocus: true %>
    </div>  
    <div class='form-group'>
      <%= f.label :URL, class: "col-sm-2 control-label" %>
      <%= f.text_field :url, class: "form-control" %>
    </div>
    <div class='form-group'>
      <%= f.label :Description, class: "col-sm-2 control-label" %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>
    </div>
    <div class='form-group'>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
    </div>

    <br/>
    <br/>

    <%= f.submit(@post.new_record? ? 'Create' : 'Edit', class: 'btn btn-success')%>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='col-md-1 box'>
  <div class="inner">
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span>
    <% end %>
    <br/>
    <span id='post_<%=post.slug%>_votes'><%= post.total_votes %> Votes</span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
    <% end %>
   </div>
</div>
<div class='col-md-11 box'>
  <div class="inner">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>By: </span><%= link_to post.creator.username, user_path(post.creator) %>
      <small>　At: <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Bookmarks' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "Most Popular" %> 

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'New Bookmark' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to 'Edit Bookmarks', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class='control-group'>
      <%= f.label :body, 'Add Comment' %>
      <%= f.text_area :body, rows: 5, class: "form-control" %>
    </div>
    <br/>
    <%= f.submit "Submit", class: 'btn btn-success' %>
  <% end %>
<% end %>

<h5>Comments:</h5>

<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> Votes")
<% else %>
  alert('You can only vote once for each post.');
<% end %>