config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do      
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  before_save :generate_slug!

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.name)
    category = Category.find_by slug: the_slug    # 同じスラッグのカテゴリーがすでにあるかどうかを確認
    count = 2
    while category && category != self            # すでにある場合は
      the_slug = append_suffix(the_slug, count)   # 下記のappend_suffixメソッドを使用
      category = Category.find_by slug: the_slug  # 変更されたスラッグと同じものがあるか確認
      count += 1
    end
    self.slug = the_slug.downcase
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0              # タイトルの最後の要素が数字の場合
      return str.split('-').slice(0...-1).join('-') + "-" + count.to_s
    else                                          # タイトルの最後の要素が数字以外の場合
      return str + "-" + count                    #　カウンターの数字を追加
    end
  end

  def to_slug(name)
    str = name.strip                              # スペースを削除
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'           # アルファベット以外をダッシュに変換
    str.gsub! /-+/, "-"                           # 重複するダッシュを1つにまとめる
    self.slug = str.downcase                      # これがないと上のgsub!がnilを返してしまう
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "A new category has been created."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by slug: params[:id]
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>
<%= render 'shared/errors', obj: @category %>

<div class='well'>
  <%= form_for @category do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit "Create", class: 'btn btn-success' %>
  <% end %>
</div>  

app/views/categories/show.html.erb
<% header = link_to('Most Popular', posts_path) + " &raquo; #{@category.name}".html_safe%>
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>