config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do      
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom:0">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarMenu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Bookmarks", root_path, :class => 'navbar-brand' %>
    </div>  
    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li>
                <%= link_to category.name, category_path(category)%>
              </li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to(new_category_path) do %>
                <i class="icon-plus"></i>
                New Category
                <% end %>
            </li>
          </ul>
        </li>
      
        <% if logged_in? %>
          <div class='nav_item'>
            <%= link_to 'Create A Bookmark', new_post_path, class: 'btn btn-success navbar-btn' %>
          </div>
        <li class="dropdown">
            <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false') do %>
              <%= current_user.username %>
              <span class='caret'></span>
            <% end %>          
          <ul class="dropdown-menu">
              <li>
                <%= link_to user_path(current_user) do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  Profile
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_path(current_user) do %>
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                  Edit Profile
                <% end %>
              </li>
              <li>
                <%= link_to logout_path do %>
                  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                  Logout
                <% end %>
              </li>
          </ul>
        </li>
        <% else %>
          <div class='nav_item'>
            <%= link_to 'Register', register_path, class: 'btn btn-success navbar-btn' %>
          </div> 
          <div class='nav_item'>
            <%= link_to 'Login', login_path, class: 'btn navbar-btn' %>
          </div> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <title>Bookmarks</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>